### ISSUE TITLE
Expand Support Window

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [tfausak/cabal-gild#103]
Cabal Gild is a package management tool and many packages have support windows greater than the last three versions of ghc. This means that they cannot use cabal-gild in their ci because `cabal install cabal-gild` will install a different versions across the ci workflows.

The cabal flag `--constraint="cabal-gild < ...` could be used but this is problematic because
- a lot of new useful features have been implemented recently that make cabal-gild usable and without those features users will not adopt cabal gild
- cabal-gild does not report failure if a pragma is not supported
- cabal-gild is not actually broken with older ghc version

The cabal flag `--allow-older=base` could be used but then there is the potential for ci builds to start failing because of  build errors for cabal-gild.
- the user has to check if the cabal-gild is actually compatible with their ghc version
- even if cabal-gild does install, it does not mean that it is not broken

**Comment by tfausak** [comment]
This is related to #99, #78, #75, and #40. 

There's no set of GHC versions that would support everyone. Any decision I make will exclude some people. The latest three major versions is typical of a lot of other tools, including all other packages that I maintain. If users want to compile Gild using an unsupported version of GHC, they can either use an older version of Gild or roll the dice with allow newer/older. 

That being said, I would encourage users _not_ to install Gild from source. I provide Linux, macOS, and Windows binaries for every release. I also maintain [cabal-gild-setup-action](https://github.com/marketplace/actions/setup-gild) for GitHub Actions.

**Comment by BebeSparkelSparkel** [comment]
I'm on OpenBSD so that probably skews my opinion. I understand your reasoning though.

**Comment by tfausak** [comment]
Note that OpenBSD is a tier 2 platform for GHC: https://gitlab.haskell.org/ghc/ghc/-/wikis/platforms 

Notably, GHC releases don't provide binaries for OpenBSD: https://www.haskell.org/ghc/download_ghc_9_10_1.html#binaries
