### ISSUE TITLE
With --io cli option, do not write if cabal file is unchanged.

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [tfausak/cabal-gild#108]
This helps speed up builds so cabal does not need to reprocess the configuration.

**Comment by tfausak** [comment]
This sounds like a duplicate of #57, which was fixed by #58 and released in [version 1.2.0.0](https://github.com/tfausak/cabal-gild/releases/tag/1.2.0.0). Which version are you using?

**Comment by BebeSparkelSparkel** [comment]
1.5.0.1 I'll have to investigate further then thanks.

**Comment by BebeSparkelSparkel** [comment]
You are correct thanks.
