### ISSUE TITLE
else/elif seem unsupported?

### ISSUE THREAD

**Issue by hseg** [tfausak/cabal-gild#109]
Consider the following MWE:
```cabal
cabal-version: 2.4
if os(mingw32)
  constraints: tar +static
else if os(mingw32)
  constraints: tar -static
elif os(mingw32)
  constraints: tar +static +win32
```
It is currently formatted as
```
cabal-version: 2.4

if os(windows)
  constraints: tar +static
else if os ( mingw32 )
  constraints: tar -static

elif os ( mingw32 )
  constraints: tar +static +win32
```
where I would expect it to be formatted as
```
cabal-version: 2.4

if os(windows)
  constraints: tar +static
elif os(windows)
  constraints: tar -static
elif os(windows)
  constraints: tar +static +win32
```
(note the spacing!)

**Comment by tfausak** [comment]
Thanks for reporting this issue! I think there's some confusion about how conditionals work in package descriptions. Prior to Cabal 2.2, `elif` wasn't supported at all. There was only `if` and `else`. So your input would be formatted like this:

``` cabal
if flag(a)
  constraints: tar +static
else
  if flag(b)
    constraints: tar -static
  else
    if flag(c)
      constraints: tar +static +win32
```

Note that nothing else can go on the line with `else`. 

Starting with Cabal 2.2, the new `elif` section was allowed. So you could write your input like this:

``` cabal
cabal-version: 2.2

if flag(a)
  constraints: tar +static
elif flag(b)
  constraints: tar -static
elif flag(c)
  constraints: tar +static +win32
```

**Comment by hseg** [comment]
On Thu, Sep 12, 2024 at 06:40:39AM GMT, Taylor Fausak wrote:
> Note that nothing else can go on the line with `else`. 

Ah, right!
```cabal
if os(mingw32)
   constraints: tar +static
else
 if os(mingw32)
      constraints: tar -static
```
indeed correctly gives
```cabal
if os(windows)
  constraints: tar +static
else
  if os(windows)
    constraints: tar -static
```

So `cabal-gild` is correctly not accepting an `else` section with anything on
its line (though it'd be nice if it either warned about this or would
automatically fix it).

> Starting with Cabal 2.2, the new `elif` section was allowed.

Fine. These are the possibilities I see for this:
- cabal-gild pretty-prints the `elif`, but warns if `cabal-version` is not
  specified to be at least 2.2
- cabal-gild automatically bumps the `cabal-version` to be at least 2.2 when
  an `elif` section is encountered
- cabal-gild desugars the `elif` if the in-file `cabal-version < 2.2` and
  pretty-prints it otherwise
- the same, but controlled by a command-line argument of what cabal version to
  target

Given the project goals, and given we probably want to avoid being too clever,
the last two options don't look very promising. Either of the first two is good
by me.

**Comment by tfausak** [comment]
Gild is very intentionally only a formatter. It does not aim to provide any validation or linting. `else foo` is syntactically valid, so Gild formats it. Similarly, `elif` is syntactically valid even for older Cabal versions, so Gild formats it. 

Cabal itself will emit an error if you provide any arguments to `else`. For example:

``` cabal
cabal-version: 2.0
name: example
version: 0
build-type: Simple

library
  if False
    x-whatever: 0
  else if False
    x-whatever: 1
```

```
Errors encountered when parsing cabal file ./example.cabal:

example.cabal:9:3: error:
`else` section has section arguments [SecArgName (Position 9 8) "if",SecArgName (Position 9 11) "False"]

    8 |     x-whatever: 0
    9 |   else if False
      |   ^
```

And it will warn about using `elif` with an unsupported version of Cabal:

``` cabal
cabal-version: 2.0
name: example
version: 0
build-type: Simple

library
  if False
    x-whatever: 0
  elif False
    x-whatever: 1
```

```
...
Warning: example.cabal:9:3: invalid subsection "elif". You should set
cabal-version: 2.2 or larger to use elif-conditionals.
...
```

**Comment by hseg** [comment]
On Thu, Sep 12, 2024 at 09:46:23AM GMT, Taylor Fausak wrote:
> Gild is very intentionally only a formatter. It does not aim to provide any validation or linting. `else foo` is syntactically valid, so Gild formats it. Similarly, `elif` is syntactically valid even for older Cabal versions, so Gild formats it. 

OK. However, the formatting for `elif` as a directive starting a conditional
section, versus a generic section-starting directive, *is* something where Gild
could err on the side of newer cabal formats on, correct?
My other musings on emitting the correct cabal-version aside, we could pretend
`elif` is a supported directive, and have cabal catch if the usage was
incorrect.
(This would remove `else if -> elif` from the table, which is a compromise I'm
willing to make)

**Comment by tfausak** [comment]
Are you asking for Gild to always format `elif`, even if the Cabal version is less than 2.2? It certainly could do that, but it deliberately doesn't: https://github.com/tfausak/cabal-gild/pull/83#discussion_r1642862115

Once the user notices the warning from Cabal, presumably they'll edit their package description to use a recent-enough Cabal version. Then all they have to do is re-run Gild and it should be formatted correctly. 

It's also worth noting that `elif os(mingw32)` and `elif os ( mingw32 )` are semantically the same. The extra spaces don't change the meaning at all.

**Comment by hseg** [comment]
I'm saying that `elif` is never formatted, even if Cabal is at least 2.2, which it seems you believe is not what's happening? How is Gild detecting the cabal version, if so?
I was suggesting Gild always format `elif` for simplicity's sake, and to leave the correctness concern to Cabal.
And yes, `elif os ( mingw32 )` is semantically identical, but I want my tools to _improve_ the formatting, not worsen it.

**Comment by tfausak** [comment]
But `elif` does get formatted?

``` cabal
-- input
cabal-version: 2.2
elif flag ( BLAH )
  x-blah: true
```

``` cabal
-- output
cabal-version: 2.2
elif flag(blah)
  x-blah: true
```

There's also a test for this case:

https://github.com/tfausak/cabal-gild/blob/f30f35eadd68366b6e3087c060df83eef09be4b2/source/test-suite/Main.hs#L660-L663

**Comment by hseg** [comment]
I could've sworn I could reproduce the issue last week, but looking back at my
scrollback and the initial file, it seems I wasn't noticing the absence of a
`cabal-version` header. My bad, sorry for the noise!

**Comment by tfausak** [comment]
No problem! Sorry for the confusion.
