### ISSUE TITLE
`discover` pragma doesn't handle Alex (`*.x`) files

### ISSUE THREAD

**Issue by vaibhavsagar** [tfausak/cabal-gild#14]
Thanks for this project! I'm trying to use it with [this repo](https://github.com/vaibhavsagar/writing-a-c-compiler/) that includes an Alex lexer, but the `discover` pragma is not including my `Lexer.x` file in `exposed-modules`. Is this something you would consider changing? I also wonder if Happy (`*.y`), `hsc2hs` (`*.hsc`), and `chs` (`*.chs`) files are also not being handled by the current implementation.

**Comment by tfausak** [comment]
The current implementation very specifically only looks for `*.hs` files:

https://github.com/tfausak/cabal-gild/blob/d5e735f0135b0f0931264d2240a565e711284ce6/source/library/CabalGild/Action/EvaluatePragmas.hs#L60

I did that on purpose because that's all I ever use. I would be happy to add support for the file extensions you listed. Are there any others? I can think of literate Haskell, which is `*.lhs`. Perhaps there's an authoritative list somewhere.

**Comment by tfausak** [comment]
Cabal seems to look for: `*.hs`, `*.lhs`, `*.hsig`, and `*.lhsig`. The last two are Backpack signatures, which I don't think can actually appear in `exposed-modules`.
https://github.com/haskell/cabal/blob/2acae632a0d625cd5b54aeb257fc83188344fa03/Cabal/src/Distribution/Simple/BuildPaths.hs#L192

I've never used Alex (or Happy or ...) before, so please forgive the ignorance. Isn't the `*.x` file used to generate a `*.hs` file? If so, I would expect Gild to pick up that `*.hs` file after it's been generated. Or maybe all this happens automatically and the generated `*.hs` file only exists under the `dist-newstyle/` directory or something.

**Comment by tfausak** [comment]
hpack looks for: `*.hs`, `*.lhs`, `*.chs`, `*.hsc`, `*.y`, `*.ly` and `*.x`. 
https://github.com/sol/hpack/blob/d4635054ecde02692eff080e515cbd70968f38f2/src/Hpack/Module.hs#L72-L78

For `*.hsig` and `*.lhsig`, I would need to add support for discovery on [the `signatures` field](https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-library-signatures). 

For the rest, I think it makes sense to support them. Are they supposed to be added to [the `autogen-modules` field](https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-autogen-modules) as well? If so, the pragma will need to support that field in addition to `exposed-modules` and `other-modules`.

**Comment by vaibhavsagar** [comment]
> I've never used Alex (or Happy or ...) before, so please forgive the ignorance. Isn't the `*.x` file used to generate a `*.hs` file? If so, I would expect Gild to pick up that `*.hs` file after it's been generated. Or maybe all this happens automatically and the generated `*.h`s file only exists under the `dist-newstyle/` directory or something.

It happens automatically, AFAICT the same is true of `hsc2hs` and `c2hs`. For example. we can see [`Network/Socket`](https://github.com/haskell/network/tree/1a8a923112f65de4d533ac8d4d2fd66c8ab5b1f5/Network/Socket) from the venerable [`network`](https://hackage.haskell.org/package/network) package.

> Are they supposed to be added to [the `autogen-modules` field](https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-autogen-modules) as well?

That's a good question, I haven't seen `autogen-modules` in the wild before (but I also haven't looked very hard) so I don't know but my suspicion is that this is a separate feature. For example the way it is used [here](https://github.com/nlander/minimal-autogen/blob/1c6a440fa213185a34ebd5a0b1870e5e73f03c10/minimal-autogen.cabal) it seems like the correct thing for `cabal-gild` to do would be to store the contents of `autogen-modules` and add them to `exposed-modules` after other processing. It doesn't seem like `cabal-gild` would have to modify `autogen-modules`.

**Comment by tfausak** [comment]
I'll leave `autogen-modules` alone until someone asks for it specifically. 

I found a list of the file extensions that Cabal cares about: https://cabal.readthedocs.io/en/3.10/cabal-package.html#modules-and-preprocessors

- `.hs` and `.lhs` (haskell)
- `.gc` (greencard)
- `.chs` (c2hs)
- `.hsc` (hsc2hs)
- `.y` and `.ly` (happy)
- `.x` (alex)
- `.cpphs` (cpphs)

So the only ones we missed were `.gc` for [GreenCard](https://hackage.haskell.org/package/greencard-3.0.4.2), which I hadn't heard of before, and `.cpphs` for [cpphs](https://hackage.haskell.org/package/cpphs-1.20.9.1), which I didn't realize was different from `{-# LANGUAGE CPP #-}`.

**Comment by vaibhavsagar** [comment]
I'm extremely skeptical that anyone still uses `GreenCard`, I'd heard of it before but only as a historical curiosity.

**Comment by tfausak** [comment]
Thanks for opening this issue! The fix from #17 have been released in [version 1.0.2.0](https://github.com/tfausak/cabal-gild/releases/tag/1.0.2.0).

**Comment by vaibhavsagar** [comment]
Thank you!!
