### ISSUE TITLE
I've created a Github Action

### ISSUE THREAD

**Issue by nikita-volkov** [tfausak/cabal-gild#32]
https://github.com/nikita-volkov/cabal-gild.github-action

**Comment by tfausak** [comment]
Awesome! 

I provide a GitHub Action for setting up Gild. From there, users can use `cabal-gild` however they'd like, whether that's formatting or checking. https://github.com/marketplace/actions/setup-gild

**Comment by nikita-volkov** [comment]
Oops. I didn't assume that you would have it all worked out by the first release :) Good job! I'll deprecate my repo.
