### ISSUE TITLE
[Feature Request] No-op when content unchanged in format mode

### ISSUE THREAD

**Issue by konn** [tfausak/cabal-gild#57]
Hi, thank you for creating this tool, I love it!

## Summary

It would be good for `cabal-gild` not to edit `*.cabal` when the file is already formatted when `--io` specified.

## Background

I used hpack extensibly before, and now I want to use `-- cabal-gild: discover src` pragma to avoid manual module generation.
I'm using VSCode, so I wanted to run `cabal-gild --io` whenever `*.hs` is saved.
So, I configured VSCode to do that with RunOnSave extension:

```settings.json
{ 
  "emeraldwalk.runonsave": {
    "commands": [
      {
        "cmd": "bash -c \"find . -name '*.cabal' -or -name 'cabal.*' -not -path './dist-newstyle/*' | while read -r FILE; do cabal-gild --io=\"\\${FILE}\"; done\"",
        "isAsync": true,
        "match": "\\.l?hs$"
      }
    ]
  }
}
```

This will apply `cabal-gild` to all `*.cabal` and `cabal.project` files whenever any hs files are created or updated.
The problem is that, as cabal-gild will override cabal files even when the result is identical to the input, HLS will restart every time I saved `*.hs` file, which is annoying when doing with large projects.

I did similar when I used `hpack` - but hpack doesn't bumps up the timestamp if the generated cabal is identical.
For the time being, I modified the settings above to run `cabal-gild` in `check` mode, and re-run `format` mode if the cabal is unformatted:

```settings.json
{ 
  "emeraldwalk.runonsave": {
    "commands": [
      {
        "cmd": "bash -c \"find . -name '*.cabal' -or -name 'cabal.*' -not -path './dist-newstyle/*' | while read -r FILE; do cabal-gild -m check -i \"\\${FILE}\" || cabal-gild --io=\"\\${FILE}\"; done\"",
        "isAsync": true,
        "match": "\\.l?hs$"
      }
    ]
  }
}
```

It would be nicer if cabal-fmt avoid such identical writing.

**Comment by tfausak** [comment]
Yeah that makes sense. I’ll see about adding it today.

**Comment by tfausak** [comment]
Release in [version 1.2.0.0](https://github.com/tfausak/cabal-gild/releases/tag/1.2.0.0).

**Comment by konn** [comment]
Thanks!
