### ISSUE TITLE
Adds main to other-modules

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [tfausak/cabal-gild#96]
I am using hspc-discovery and the file Spec.hs has the main function and is not a module. `cabal-gild` adds `Spec` to `other-modules` causing the error

```txt
tests/Spec.hs:3:8: error:
    File name does not match module name:
    Saw: _Main_
    Expected: _Spec_
```

Non-modules should not be added to other modules especially if the file is listed with `main-is: Spec.hs`

**Comment by tfausak** [comment]
Can you exclude the `Spec` module from Gild's discovery?

``` cabal
-- cabal-gild: discover tests --exclude=tests/Spec.hs
```

**Comment by BebeSparkelSparkel** [comment]
Thanks for the tip of using the exact path.

I had tried exclude with glob patterns as specified in the [README](https://github.com/tfausak/cabal-gild/blob/f30f35eadd68366b6e3087c060df83eef09be4b2/README.md?plain=1#L266) but the patterns do not seem to work.

```
-- cabal-gild: discover tests --exclude=**/Spec.hs
-- cabal-gild: discover tests --exclude=*/Spec.hs
```

**Comment by tfausak** [comment]
Which version are you using? Support for excluding patterns was added in Gild 1.3.2.0.

**Comment by BebeSparkelSparkel** [comment]
1.3.1.1
